package com.example.weather_friend1.ui

  class Cites() {

val citesList = listOf<String>(
                                 "Yanbu",
                                 "Umluj",
                                 "Umm as Sāhik",
                                 "Turaif",
                                 "Turabah",
                                 "At Tūbī",
                                 "Tārūt",
                                 "Tanūmah",
                                 "Tamrah",
                                 "Minţaqat Tabūk",
                                 "Tabuk",
                                 "Ţubarjal",
                                 "Tabālah",
                                 "Şumaymah",
                                 "Sulţānah",
                                 "Sufan",
                                 "Sīdī Ḩamzah",
                                 "Sayhāt",
                                 "Kingdom of Saudi Arabia",
                                 "Şāmitah",
                                 "Sakakah",
                                 "Şafwá",
                                 "Şabyā",
                                 "Ras Tanura",
                                 "Raḩīmah",
                                 "Rafha",
                                 "Rābigh",
                                 "Qārā",
                                 "Qal‘at Bīshah",
                                 "Nimrān",
                                 "Najrān",
                                 "Naghbī",
                                 "Mulayjah",
                                 "Mislīyah",
                                 "Masjid Ibn Rashīd",
                                 "Masāḩilī",
                                 "Marāt",
                                 "Makkah Province",
                                 "Mecca",
                                 "Madīnat Yanbu‘ aş Şinā‘īyah",
                                 "Khamis Mushait",
                                 "Julayjilah",
                                 "Jizan Region",
                                 "Jizan",
                                 "Jeddah",
                                 "Ḩajlah",
                                 "Hai’l Region",
                                 "Ha'il",
                                 "Hafar Al-Batin",
                                 "Farasān",
                                 "Duba",
                                 "Buraydah",
                                 "Abqaiq",
                                 "Birzayn",
                                 "Banbān",
                                 "Badr Ḩunayn",
                                 "Az Zulfī",
                                 "Dhahran",
                                 "Aţ Ţaraf",
                                 "Ta’if",
                                 "As Sulayyil",
                                 "As Sulaymānīyah",
                                 "Sājir",
                                 "As Saffānīyah",
                                 "Minţaqat ‘Asīr",
                                 "Ash Shurayf",
                                 "Ash Shubramīyah",
                                 "Al Minţaqah ash Sharqīyah",
                                 "Ar Ruqayyiqah",
                                 "Riyadh",
                                 "Minţaqat ar Riyāḑ",
                                 "Ar Rass",
                                 "Arar",
                                 "An Nimāş",
                                 "Qurayyat",
                                 "Al Wajh",
                                 "Al Qurayn",
                                 "Qaisumah",
                                 "Al Qaţīf",
                                 "Al-Qassim Province",
                                 "Al Quraynah",
                                 "Al Qārah",
                                 "Al Muţayrifī",
                                 "Al Munayzilah",
                                 "Al Mubarraz",
                                 "Al Mindak",
                                 "Al Mikhlāf",
                                 "Al Markaz",
                                 "Medina",
                                 "Al Madīnah al Munawwarah",
                                 "Khobar",
                                 "Al Kharj",
                                 "Al Khafjī",
                                 "Al Jumūm",
                                 "Al Jubayl",
                                 "Al Jubayl",
                                 "Al Jawf",
                                 "Al Jarādīyah",
                                 "Al Jafr",
                                 "Al Hufūf",
                                 "Minţaqat al Ḩudūd ash Shamālīyah",
                                 "Al Ghaţghaţ",
                                 "Al Bukayrīyah",
                                 "Al Baţţālīyah",
                                 "Al Buşur",
                                 "Al Bahah",
                                 "Al Arţāwīyah",
                                 "Al ‘Aqīq",
                                 "Al Awjām",
                                 "Afif",
                                 "Ad Dilam",
                                 "Ad Dawādimī",
                                 "Ad Darb",
                                 "Dammam",
                                 "Abū ‘Arīsh",
                                 "Abha",
                                 "Abā as Su‘ūd",
                                 "Ash Shu‘aybah",
                                 "Ḩajrat al Khinbish",
                                 "‘Uşayfirāt",
                                 "Al Fāḑilī",
                                 "Şuwayr",
                                 "Sidīs",
                                 "Khushaybī al Ḩaḑar",
                                 "Tumayr",
                                 "Al Fuwayliq",
                                 "Al Majāridah",
                                 "Al Fayşalīyah",
                                 "As Sahbā’",
                                 "Al ‘Awājīyah",
                                 "Raḑwān",
                                 "Al Muwayh",
                                 "Al Hadā",
                                 "Mizhirah",
                                 "Al Mudawwarah",
                                 "Al Ābār",
                                 "Al Qudayḩ",
                                 "Al Khālidīyah",
                                 "shokhaibٍ",
                                 "Sharurah"
                               )









}